function [thrust_lbf, TSFC, T4_check] = run_cycle(engine, alt_ft, Mach, TIT)
%RUN_CYCLE Evaluates a separate-flow turbofan cycle.
%
% Inputs:
%   engine - structure containing engine and component parameters
%   alt_ft - flight altitude in feet
%   Mach   - flight Mach number
%   TIT    - turbine inlet temperature in kelvin
%
% If TIT is omitted or supplied as empty, the engine's design-point TIT is
% used automatically.
%
% Examples:
%   engine = load_engine("CFM56-7B");
%
%   % Use the engine design TIT:
%   [thrust, TSFC] = run_cycle(engine, 35000, 0.8);
%
%   % Override the design TIT:
%   [thrust, TSFC] = run_cycle(engine, 35000, 0.8, 1600);

    %% Optional TIT input
    if nargin < 4 || isempty(TIT)
        TIT = engine.TIT_design;
    end

    %% Extract properties from the engine structure
    gamma_air = engine.gamma_air;
    Cp_air = engine.Cp_air;

    gamma_gas = engine.gamma_gas;
    Cp_gas = engine.Cp_gas;

    FPR = engine.FPR;
    eta_fan = engine.eta_fan;

    PR_LPC = engine.PR_LPC;
    eta_LPC = engine.eta_LPC;

    PR_HPC = engine.PR_HPC;
    eta_HPC = engine.eta_HPC;

    pressure_loss_frac = engine.combustor_pressure_loss;
    LHV_fuel = engine.LHV_fuel;
    eta_combustor = engine.eta_combustor;

    eta_HPT = engine.eta_HPT;
    mech_eff_HP = engine.mech_eff_HP;

    eta_LPT = engine.eta_LPT;
    mech_eff_LP = engine.mech_eff_LP;

    eta_nozzle_core = engine.eta_nozzle_core;
    eta_nozzle_bypass = engine.eta_nozzle_bypass;

    BPR = engine.BPR;
    fan_diameter = engine.fan_diameter;

    %% Station 0: freestream
    alt_m = alt_ft * 0.3048;

    [T0, a0, P0, rho0] = atmosisa(alt_m);

    V0 = Mach * a0;

    T0_stag = T0 * ...
        (1 + (gamma_air - 1)/2 * Mach^2);

    P0_stag = P0 * ...
        (1 + (gamma_air - 1)/2 * Mach^2)^...
        (gamma_air/(gamma_air - 1));

    %% Fan
    [T2_stag, P2_stag, T13_stag, P13_stag, fan_work] = ...
        fan_compression( ...
            T0_stag, ...
            P0_stag, ...
            FPR, ...
            eta_fan, ...
            Cp_air, ...
            gamma_air);

    %% Low-pressure compressor
    [T25_stag, P25_stag, LPC_work] = ...
        compressor_stage( ...
            T2_stag, ...
            P2_stag, ...
            PR_LPC, ...
            eta_LPC, ...
            Cp_air, ...
            gamma_air);

    %% High-pressure compressor
    [T3_stag, P3_stag, HPC_work] = ...
        compressor_stage( ...
            T25_stag, ...
            P25_stag, ...
            PR_HPC, ...
            eta_HPC, ...
            Cp_air, ...
            gamma_air);

    %% Combustor
    [T4_stag, P4_stag, f] = ...
        combustor( ...
            T3_stag, ...
            P3_stag, ...
            TIT, ...
            pressure_loss_frac, ...
            Cp_gas, ...
            LHV_fuel, ...
            eta_combustor);

    %% High-pressure turbine
    % The HPT provides the power required by the HPC.
    [T45_stag, P45_stag, ~] = ...
        turbine_stage( ...
            T4_stag, ...
            P4_stag, ...
            HPC_work, ...
            eta_HPT, ...
            mech_eff_HP, ...
            Cp_gas, ...
            gamma_gas);

    %% Low-pressure turbine
    % The LPT drives both the LPC and the fan.
    LPT_work_required = LPC_work + fan_work;

    [T5_stag, P5_stag, ~] = ...
        turbine_stage( ...
            T45_stag, ...
            P45_stag, ...
            LPT_work_required, ...
            eta_LPT, ...
            mech_eff_LP, ...
            Cp_gas, ...
            gamma_gas);

    %% Core and bypass nozzles
    [V8, T8, P8, ~] = ...
        nozzle( ...
            T5_stag, ...
            P5_stag, ...
            P0, ...
            Cp_gas, ...
            gamma_gas, ...
            eta_nozzle_core);

    [V18, T18, P18, ~] = ...
        nozzle( ...
            T13_stag, ...
            P13_stag, ...
            P0, ...
            Cp_air, ...
            gamma_air, ...
            eta_nozzle_bypass);

    %% Mass-flow estimate

    % Base inlet capture ratio
    base_capture_ratio = interp1( ...
        engine.capture_Mach_points, ...
        engine.capture_ratio_points, ...
        Mach, ...
        'linear', ...
        'extrap');

    % Engine-specific correction factor
    inlet_mass_flow_ratio = ...
        engine.capture_scale * base_capture_ratio;

    % Fan area
    A_fan = pi/4 * fan_diameter^2;

    % Total mass flow
    mdot_total = ...
        inlet_mass_flow_ratio * rho0 * A_fan * V0;

    % Core and bypass mass flow
    mdot_core = ...
        mdot_total / (1 + BPR);

    mdot_bypass = ...
        mdot_total * BPR / (1 + BPR);

    % Fuel mass flow
    mdot_fuel = ...
        mdot_core * f;

    %% Momentum thrust

    F_core_mom = ...
        (mdot_core + mdot_fuel) * V8 ...
        - mdot_core * V0;

    F_bypass_mom = ...
        mdot_bypass * V18 ...
        - mdot_bypass * V0;

    %% Pressure thrust

    rho8 = P8 / (287 * T8);

    A8 = ...
        (mdot_core + mdot_fuel) / ...
        (rho8 * V8);

    F_pressure_core = ...
        (P8 - P0) * A8;

    rho18 = P18 / (287 * T18);

    A18 = ...
        mdot_bypass / ...
        (rho18 * V18);

    F_pressure_bypass = ...
        (P18 - P0) * A18;

    %% Total thrust

    F_total = ...
        F_core_mom ...
        + F_pressure_core ...
        + F_bypass_mom ...
        + F_pressure_bypass;

    %% Pressure thrust
    rho8 = P8 / (287 * T8);

    A8 = ...
        (mdot_core + mdot_fuel) / ...
        (rho8 * V8);

    F_pressure_core = ...
        (P8 - P0) * A8;

    rho18 = P18 / (287 * T18);

    A18 = ...
        mdot_bypass / ...
        (rho18 * V18);

    F_pressure_bypass = ...
        (P18 - P0) * A18;

    %% Total thrust
    F_total = ...
        F_core_mom ...
        + F_pressure_core ...
        + F_bypass_mom ...
        + F_pressure_bypass;

    %% Convert outputs
    thrust_lbf = F_total * 0.2248;

    mdot_fuel_lbhr = ...
        mdot_fuel * 3600 * 2.2046;

    TSFC = mdot_fuel_lbhr / thrust_lbf;

    T4_check = T4_stag;
end